apiVersion: v1
kind: Service
metadata:
  name: pandita
  labels:
    app: pandita
spec:
  selector:
    app: pandita
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  # type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10811
