apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandita
  labels:
    app: pandita
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pandita
  template:
    metadata:
      labels:
        app: pandita
    spec:
      containers:
      - image: pandita:release
        name: pandita
        imagePullPolicy: Always
        ports:
        - containerPort: 10811
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "450m"
        env:
        - name: DB_HOST
          value: "YOU SHOULD FILL IT"
        - name: DB_PORT
          value: "14000"
        - name: DB_NAME
          value: "pandita" 
        - name: DB_USER
          value: "cbteam"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pandita-secret
              key: DB_PASS
        - name: DB_RETRY
          value: "True"
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
        readinessProbe:
          httpGet:
            path: /healthCheck
            port: 10811
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
